# Setup

In [1]:
import pandas as pd

## Todos Datasets
![SERS_Datasets.svg]()

No dataset_5, não utilizei o select columns porque no arquivo baixado já tinha as informações necessarias, não precisou tirar nada

# Dataset 1 — Appliances Energy Prediction (UCI)
 Situação

Uma empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

In [ ]:
# 1.Carregue a amostra no Pandas e apresente head(), shape, info() e describe().
dataset_1 = pd.read_csv('energy_data_complete.csv')

dataset_1.head()

   Appliances  lights       T1     RH_1       T2     RH_2       T3     RH_3
0          40       0  20.8900  35.4000  17.7600  39.1633  20.2900  36.9000
1          90      10  21.8900  53.1000  21.2900  45.3600  21.6333  49.2267
2          50       0  21.3900  35.5000  17.6333  40.5300  21.6667  35.2000
3          50       0  21.3900  41.0333  23.8900  34.8400  22.0333  36.9333
4          70       0  19.9633  35.1267  16.4633  40.1267  20.0000  36.4000

In [ ]:
dataset_1.shape

(13815, 8)

In [ ]:
dataset_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13815 entries, 0 to 13814
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  13815 non-null  int64
 1   lights      13815 non-null  int64
 2   T1          13815 non-null  float64
 3   RH_1        13815 non-null  float64
 4   T2          13815 non-null  float64
 5   RH_2        13815 non-null  float64
 6   T3          13815 non-null  float64
 7   RH_3        13815 non-null  float64
dtypes: float64(6), int64(2)
memory usage: 863.6 KB

In [ ]:
dataset_1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,13815.000000,13815.000000,13815.000000,13815.000000,13815.000000,13815.000000,13815.000000,13815.000000
mean,98.359030,3.788636,21.688826,40.246119,20.350795,40.386394,22.266142,39.229219
std,103.636465,7.907195,1.599638,4.000603,2.189883,4.077668,1.998616,3.258592
min,10.000000,0.000000,16.790000,27.023300,16.100000,20.463300,17.200000,29.293300
25%,50.000000,0.000000,20.760000,37.326700,18.823300,37.790000,20.790000,36.900000
50%,60.000000,0.000000,21.600000,39.626700,20.000000,40.463300,22.100000,38.500000
75%,100.000000,0.000000,22.600000,43.050000,21.533300,43.230000,23.290000,41.730000
max,1080.000000,70.000000,26.260000,63.360000,29.856700,56.026700,29.236000,49.800000

In [ ]:
# 2.Renomeie Appliances para Consumo_Eletrodomesticos e simplifique o nome de pelo menos três atributos ambientais.
dataset_1.rename(columns={'Appliances': 'Consumo_Eletrodomesticos',
                          'T1': 'Temperatura_1',
                          'T2': 'Temperatura_2',
                          'T3': 'Temperatura_3'}, inplace = True)

In [ ]:
# 3.Determine o maior consumo de eletrodomésticos registrado na amostra.
maior_consumo_1 = dataset_1['Consumo_Eletrodomesticos'].max()

print(f'O maior consumo de eletrodomésticos registrado na amostra foi de: {maior_consumo_1} Wh')

O maior consumo de eletrodomésticos registrado na amostra foi de: 1080 Wh

In [ ]:
# 4.Calcule um limiar correspondente a 70% do valor máximo e crie um DataFrame contendo somente os registros acima desse limite.
limiar_70_1 = maior_consumo_1 * 0.70

print(f'O limiar de 70% do consumo máximo é: {limiar_70_1} Wh')

dataset_acima_70_1 = dataset_1[
    dataset_1['Consumo_Eletrodomesticos'] > limiar_70_1]

print(dataset_acima_70_1.head())

O limiar de 70% do consumo máximo é: 756.0 Wh
      Consumo_Eletrodomesticos  lights  Temperatura_1     RH_1  Temperatura_2  \
1733                       770      20          20.20  40.5000        19.2900
2881                       900       0          23.00  43.1667        22.2000
3220                       800       0          22.10  41.7000        21.2000
3349                       820       0          22.50  47.8667        21.2300
5044                       890      20          19.73  37.8633        18.5667

         RH_2  Temperatura_3     RH_3
1733  40.4333        20.5000  39.1567
2881  40.4267        26.1000  38.9300
3220  41.7900        23.2000  38.2600
3349  45.6567        25.0333  39.7900
5044  34.0900        18.3900  36.8633

In [ ]:
# 5.Conte os registros selecionados e calcule qual percentual da amostra eles representam.
quantidade_acima_70_1 = dataset_acima_70_1.shape[0]

quantidade_total_1 = dataset_1.shape[0]

percentual_acima_70_1 = (quantidade_acima_70_1 / quantidade_total_1) * 100

print(f'Quantidade de registros acima de 70%: {quantidade_acima_70_1}')
print(f'Quantidade total de registros: {quantidade_total_1}')
print(f'Percentual da amostra: {percentual_acima_70_1:.2f}%')

Quantidade de registros acima de 70%: 22
Quantidade total de registros: 13815
Percentual da amostra: 0.16%

In [ ]:
# 6.Calcule a temperatura média de T1 e crie outro DataFrame
# contendo simultaneamente consumo acima de 70% do máximo e temperatura acima da média.
temperatura_media_1 = dataset_1['Temperatura_1'].mean()

print(f'A temperatura média de T1 foi: {temperatura_media_1:.2f} °C')

A temperatura média de T1 foi: 21.69 °C

In [ ]:
dataset_acima_70_e_temp_media_1 = dataset_1[
    (dataset_1['Consumo_Eletrodomesticos'] > limiar_70_1) &
    (dataset_1['Temperatura_1'] > temperatura_media_1)]

print(dataset_acima_70_e_temp_media_1.head())

      Consumo_Eletrodomesticos  lights  Temperatura_1     RH_1  Temperatura_2  \
2881                       900       0        23.0000  43.1667          22.20
3220                       800       0        22.1000  41.7000          21.20
3349                       820       0        22.5000  47.8667          21.23
5779                       790       0        22.3900  45.5633          22.39
5903                       770       0        22.8233  48.7633          22.39

         RH_2  Temperatura_3     RH_3
2881  40.4267        26.1000  38.9300
3220  41.7900        23.2000  38.2600
3349  45.6567        25.0333  39.7900
5779  42.9667        25.0000  41.4333
5903  39.8000        23.2900  39.2300

In [ ]:
# 7.Compare os dois DataFrames e explique o efeito da inclusão da temperatura como segundo critério.
registro_1_1 = dataset_acima_70_1.shape[0]
registro_2_1 = dataset_acima_70_e_temp_media_1.shape[0]

print(f'Registros com consumo acima de 70%: {registro_1_1}')
print(f'Registros com consumo acima de 70% e temperatura acima da média: {registro_2_1}')

print(f'Registros eliminados pela inclusão da temperatura: {registro_1_1 - registro_2_1}')

Registros com consumo acima de 70%: 22
Registros com consumo acima de 70% e temperatura acima da média: 10
Registros eliminados pela inclusão da temperatura: 12

# Dataset 2 — Steel Industry Energy Consumption (UCI)
Situação

A equipe de gestão de energia de uma indústria siderúrgica deseja localizar situações de consumo elevado e verificar se esses períodos coincidem com condições de carga elevada ou valores menos favoráveis de fator de potência.

In [ ]:
dataset_2 = pd.read_csv('Steel_industry_data.csv')

In [ ]:
# 1.Carregar o dataset e renomear as colunas

dataset_2.rename(columns={
    'Usage_kWh': 'Consumo_kWh',
    'Lagging_Current_Reactive.Power_kVarh': 'Potencia_Reativa_Atrasada',
    'Leading_Current_Reactive_Power_kVarh': 'Potencia_Reativa_Adiantada',
    'Lagging_Current_Power_Factor': 'Fator_Potencia_Atrasado',
    'Leading_Current_Power_Factor': 'Fator_Potencia_Adiantado'}, inplace=True)

In [ ]:
# 2.Inspeção inicial
dataset_2.head()

,Consumo_kWh,Potencia_Reativa_Atrasada,Potencia_Reativa_Adiantada,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
0,2.88,3.82,0.0,60.20,100.00,Weekend,Sunday,Light_Load
1,60.77,48.02,0.0,78.46,100.00,Weekday,Thursday,Maximum_Load
2,120.42,59.65,0.0,89.61,100.00,Weekday,Friday,Maximum_Load
3,3.13,0.00,16.6,100.00,18.53,Weekend,Saturday,Light_Load
4,58.86,20.99,0.0,94.19,100.00,Weekday,Friday,Medium_Load

In [ ]:
dataset_2.shape

(7008, 8)

In [ ]:
dataset_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7008 entries, 0 to 7007
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Consumo_kWh                 7008 non-null   float64
 1   Potencia_Reativa_Atrasada   7008 non-null   float64
 2   Potencia_Reativa_Adiantada  7008 non-null   float64
 3   Fator_Potencia_Atrasado     7008 non-null   float64
 4   Fator_Potencia_Adiantado    7008 non-null   float64
 5   WeekStatus                  7008 non-null   object
 6   Day_of_week                 7008 non-null   object
 7   Load_Type                   7008 non-null   object
dtypes: float64(5), object(3)
memory usage: 438.1+ KB

In [ ]:
dataset_2.describe()

,Consumo_kWh,Potencia_Reativa_Atrasada,Potencia_Reativa_Adiantada,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado
count,7008.000000,7008.000000,7008.000000,7008.000000,7008.000000
mean,27.790164,13.206839,3.803711,80.672277,84.491448
std,33.717719,16.444246,7.356412,18.869855,30.314798
min,2.450000,0.000000,0.000000,37.870000,12.710000
25%,3.200000,2.380000,0.000000,63.602500,99.710000
50%,4.570000,5.040000,0.000000,87.990000,100.000000
75%,52.107500,22.977500,1.857500,98.842500,100.000000
max,153.140000,87.700000,27.650000,100.000000,100.000000

In [ ]:
# 3.Maior consumo e limiar de 75%
maior_consumo_2 = dataset_2['Consumo_kWh'].max()

limiar_75_2 = maior_consumo_2 * 0.75

print(f'O maior consumo registrado foi de: {maior_consumo_2:.2f} kWh')
print(f'O limiar de 75% do consumo máximo é: {limiar_75_2:.2f} kWh')

O maior consumo registrado foi de: 153.14 kWh
O limiar de 75% do consumo máximo é: 114.85 kWh

In [ ]:
# 4.Crie um DataFrame contendo os registros acima desse limiar
# calcule a quantidade e o percentual de registros.
dataset_consumo_elevado_2 = dataset_2[
    dataset_2['Consumo_kWh'] > limiar_75_2]

display(dataset_consumo_elevado_2.head())

,Consumo_kWh,Potencia_Reativa_Atrasada,Potencia_Reativa_Adiantada,Fator_Potencia_Atrasado,Fator_Potencia_Adiantado,WeekStatus,Day_of_week,Load_Type
2,120.42,59.65,0.0,89.61,100.0,Weekday,Friday,Maximum_Load
62,118.22,54.04,0.0,90.95,100.0,Weekday,Thursday,Medium_Load
100,129.13,46.58,0.0,94.07,100.0,Weekday,Monday,Medium_Load
108,117.07,46.44,0.0,92.95,100.0,Weekday,Monday,Medium_Load
159,139.57,58.90,0.0,92.13,100.0,Weekday,Thursday,Maximum_Load

In [ ]:
quantidade_consumo_elevado_2 = dataset_consumo_elevado_2.shape[0]

quantidade_total_2 = dataset_2.shape[0]

percentual_consumo_elevado_2 = (quantidade_consumo_elevado_2 / quantidade_total_2) * 100

print(f'Quantidade de registros com consumo elevado: {quantidade_consumo_elevado_2}')
print(f'Quantidade total de registros: {quantidade_total_2}')
print(f'Percentual da amostra: {percentual_consumo_elevado_2:.2f}%')

Quantidade de registros com consumo elevado: 129
Quantidade total de registros: 7008
Percentual da amostra: 1.84%

In [ ]:
# 5.Verifique quantos registros desse DataFrame pertencem à categoria Maximum Load.
quantidade_maximum_load_2 = (
    dataset_consumo_elevado_2['Load_Type'] == 'Maximum_Load').sum()

print(f'Registros de consumo elevado pertencentes a Maximum Load: {quantidade_maximum_load_2}')

Registros de consumo elevado pertencentes a Maximum Load: 62

In [ ]:
dataset_consumo_elevado_2['Load_Type'].value_counts()

Load_Type
Maximum_Load    62
Medium_Load     58
Light_Load       9
Name: count, dtype: int64

In [ ]:
# 6.Escolha um dos atributos de fator de potência, observe seus valores
# defina um limite coerente para representar valores mais baixos.
limite_fator_potencia_2 =  80
print(f'Limite escolhido para o fator de potência: {limite_fator_potencia_2}')

dataset_2['Fator_Potencia_Atrasado'].sort_values()

Limite escolhido para o fator de potência: 80

5214     37.87
2024     39.10
3413     39.27
1266     39.36
5078     40.05
         ...
30      100.00
24      100.00
23      100.00
6997    100.00
7000    100.00
Name: Fator_Potencia_Atrasado, Length: 7008, dtype: float64

In [ ]:
# 7.Crie um novo DataFrame
# contendo simultaneamente consumo elevado e fator de potência abaixo do limite escolhido.
dataset_atencao_energia_2 = dataset_2[
    (dataset_2['Consumo_kWh'] > limiar_75_2) &
    (dataset_2['Fator_Potencia_Atrasado'] < limite_fator_potencia_2)]

dataset_atencao_energia_2.head()

Empty DataFrame
Columns: [Consumo_kWh, Potencia_Reativa_Atrasada, Potencia_Reativa_Adiantada, Fator_Potencia_Atrasado, Fator_Potencia_Adiantado, WeekStatus, Day_of_week, Load_Type]
Index: []

In [ ]:
quantidade_atencao_2 = dataset_atencao_energia_2.shape[0]

print(f'Quantidade de registros com consumo elevado e fator de potência baixo: {quantidade_atencao_2}')
percentual_atencao_2 = (quantidade_atencao_2 / quantidade_total_2) * 100

print(f'Percentual da amostra: {percentual_atencao_2:.2f}%')

Quantidade de registros com consumo elevado e fator de potência baixo: 0
Percentual da amostra: 0.00%

In [ ]:
# 8.Explique por que esse segundo conjunto de registros
# pode merecer maior atenção da equipe de energia.

print('Os registros representam situações que combinam consumo elevado com fator '
'de potência abaixo de 80. Esses períodos merecem maior atenção porque '
'apresentam simultaneamente uma demanda elevada de energia e uma condição menos favorável de '
'fator de potência. A análise desse caso pode ajudar a identificar períodos ou equipamentos '
'que estejam contribuindo para uma utilização menos eficiente do sistema elétrico.')

Os registros representam situações que combinam consumo elevado com fator de potência abaixo de 80. Esses períodos merecem maior atenção porque apresentam simultaneamente uma demanda elevada de energia e uma condição menos favorável de fator de potência. A análise desse caso pode ajudar a identificar períodos ou equipamentos que estejam contribuindo para uma utilização menos eficiente do sistema elétrico.

# Dataset 3 — Power Consumption of Tetouan City (UCI)

Situação

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda.

In [ ]:
dataset_3 = pd.read_csv('Tetuan City power consumption.csv')

In [ ]:
# 1.Renomeie as três variáveis de consumo
# para Consumo_Zona_1, Consumo_Zona_2 e Consumo_Zona_3
dataset_3.rename(columns={
                          'Zone 1 Power Consumption': 'Consumo_Zona_1',
                          'Zone 3  Power Consumption': 'Consumo_Zona_3',
                          'Zone 2  Power Consumption': 'Consumo_Zona_2',
                          'Temperature': 'Temperatura',
                          'Humidity': 'Umidade',
                          'Wind Speed': 'Velocidade_Vento',}, inplace=True)

In [ ]:
# 2.Determine o consumo máximo registrado em cada uma das três zonas.
max_zona_1_3 = dataset_3['Consumo_Zona_1'].max()
max_zona_2_3 = dataset_3['Consumo_Zona_2'].max()
max_zona_3_3 = dataset_3['Consumo_Zona_3'].max()

print(f'Máximo da Zona 1: {max_zona_1_3:.2f}')
print(f'Máximo da Zona 2: {max_zona_2_3:.2f}')
print(f'Máximo da Zona 3: {max_zona_3_3:.2f}')

Máximo da Zona 1: 52146.86
Máximo da Zona 2: 37408.90
Máximo da Zona 3: 47598.30

In [ ]:
# 3.Identifique qual zona apresenta o maior pico de consumo na amostra.
maximos_3 = {
    'Consumo_Zona_1': max_zona_1_3,
    'Consumo_Zona_2': max_zona_2_3,
    'Consumo_Zona_3': max_zona_3_3
}

zona_maior_pico_3 = max(maximos_3, key=maximos_3.get)
maior_pico_3 = maximos_3[zona_maior_pico_3]

print(f'A zona com maior pico de consumo é: {zona_maior_pico_3}')
print(f'O maior pico registrado foi: {maior_pico_3:.2f}')

A zona com maior pico de consumo é: Consumo_Zona_1
O maior pico registrado foi: 52146.86

In [ ]:
# 4.Para a zona identificada, calcule 70% do valor máximo e
# crie um DataFrame com os registros acima desse limiar.
limiar_70_3 = maior_pico_3 * 0.70

print(f'O limiar de 70% do maior pico é: {limiar_70_3:.2f}')

O limiar de 70% do maior pico é: 36502.80

In [ ]:
dataset_consumo_elevado_3 = dataset_3[
    dataset_3[zona_maior_pico_3] > limiar_70_3]

dataset_consumo_elevado_3.head()

,Temperatura,Umidade,Velocidade_Vento,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
3,12.42,72.30,0.081,42476.93617,23634.1,25089.7
8,14.66,65.92,0.075,37286.69202,30716.2,15834.8
12,21.03,86.50,0.068,40993.90728,25383.4,24960.0
14,27.06,47.58,4.905,37475.16093,24276.2,25140.6
19,19.20,65.81,4.924,40676.02649,24754.7,25095.9

In [ ]:
# 5.Conte os registros e calcule o percentual que eles representam.
quantidade_elevada_3 = dataset_consumo_elevado_3.shape[0]

quantidade_total_3 = dataset_3.shape[0]

percentual_elevado_3 = (quantidade_elevada_3 / quantidade_total_3) * 100

print(f'Quantidade de registros acima de 70%: {quantidade_elevada_3}')
print(f'Quantidade total de registros: {quantidade_total_3}')
print(f'Percentual da amostra: {percentual_elevado_3:.2f}%')

Quantidade de registros acima de 70%: 10426
Quantidade total de registros: 36692
Percentual da amostra: 28.41%

In [ ]:
# 6.Calcule a temperatura média e crie um segundo DataFrame
# contendo consumo acima do limiar e temperatura acima da média.
temperatura_media_3 = dataset_3['Temperatura'].mean()

print(f'A temperatura média da amostra é: {temperatura_media_3:.2f} °C')

A temperatura média da amostra é: 18.82 °C

In [ ]:
dataset_consumo_e_temperatura_3 = dataset_3[
    (dataset_3[zona_maior_pico_3] > limiar_70_3) &
    (dataset_3['Temperatura'] > temperatura_media_3)
]
quantidade_segundo_3 = dataset_consumo_e_temperatura_3.shape[0]

percentual_segundo_3 = (quantidade_segundo_3 / quantidade_total_3) * 100

print(f'Quantidade de registros: {quantidade_segundo_3}')
print(f'Percentual da amostra: {percentual_segundo_3:.2f}%')

dataset_consumo_e_temperatura_3.head()

Quantidade de registros: 7024
Percentual da amostra: 19.14%

,Temperatura,Umidade,Velocidade_Vento,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
12,21.03,86.50,0.068,40993.90728,25383.4,24960.0
14,27.06,47.58,4.905,37475.16093,24276.2,25140.6
19,19.20,65.81,4.924,40676.02649,24754.7,25095.9
21,27.11,43.35,4.906,40256.07103,27416.3,25453.5
25,26.92,70.20,4.909,36511.89369,25906.3,25654.9

In [ ]:
# 7.Compare os dois conjuntos e explique o que ocorreu com a quantidade de registros
# após a inclusão da condição ambiental.
print(f'Registros com consumo acima de 70%: {quantidade_elevada_3}')

print(f'Registros com consumo acima de 70% e temperatura acima da média: {quantidade_segundo_3}')

print(f'Registros eliminados pela inclusão da temperatura: {quantidade_elevada_3 - quantidade_segundo_3}')

Registros com consumo acima de 70%: 10426
Registros com consumo acima de 70% e temperatura acima da média: 7024
Registros eliminados pela inclusão da temperatura: 3402

# Dataset 4 — Solar Power Generation Data (Kaggle)

Situação

Uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e identificar quais inversores aparecem com maior frequência nesses momentos. Nesta atividade, o foco inicial será o arquivo de geração da planta, sem realizar junção com o arquivo de sensores.

In [ ]:
# 1.Carregue a amostra e renomeie as principais variáveis para nomes
# mais claros, como Potencia_CC, Potencia_CA e Geracao_Diaria.
dataset_4 = pd.read_csv('Plant_1_Generation_Data.csv')

dataset_4.rename(columns={
    'DATE_TIME': 'Data_Hora',
    'SOURCE_KEY': 'Inversor',
    'DC_POWER': 'Potência_CC',
    'AC_POWER': 'Potência_CA',
    'DAILY_YIELD': 'Geração_Diaria',
    'TOTAL_YIELD': 'Geração_Total'}, inplace=True)

In [ ]:
# 2.Apresente head(), shape, info() e describe()

dataset_4.head()

,Data_Hora,Inversor,Potência_CC,Potência_CA,Geração_Diaria,Geração_Total
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

In [ ]:
dataset_4.shape

(48145, 6)

In [ ]:
dataset_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48145 entries, 0 to 48144
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Data_Hora       48145 non-null  object
 1   Inversor        48145 non-null  object
 2   Potência_CC     48145 non-null  float64
 3   Potência_CA     48145 non-null  float64
 4   Geração_Diaria  48145 non-null  float64
 5   Geração_Total   48145 non-null  float64
dtypes: float64(4), object(2)
memory usage: 2.2+ MB

In [ ]:
dataset_4.describe()

        Potência_CC   Potência_CA  Geração_Diaria  Geração_Total
count  48145.000000  48145.000000    48145.000000   4.814500e+04
mean    3140.159671    307.099781     3309.727017   6.978001e+06
std     4026.857247    393.466838     3145.977341   4.171417e+05
min        0.000000      0.000000        0.000000   6.183645e+06
25%        0.000000      0.000000        0.000000   6.509939e+06
50%      422.375000     40.825000     2695.380000   7.146306e+06
75%     6343.290000    621.386000     6288.880000   7.269333e+06
max    14471.100000   1410.950000     9163.000000   7.846821e+06

In [ ]:
# 3.Determine a maior potência CA registrada.
maior_potencia_ca_4 = dataset_4['Potência_CA'].max()

print(f'A maior potência CA registrada foi: {maior_potencia_ca_4:.2f}')

A maior potência CA registrada foi: 1410.95

In [ ]:
# 4.Calcule um limiar correspondente a 70% da potência CA máxima.
limiar_70_4 = maior_potencia_ca_4 * 0.70

print(f'O limiar de 70% da potência CA máxima é: {limiar_70_4:.2f}')

O limiar de 70% da potência CA máxima é: 987.66

In [ ]:
# 5.Crie um DataFrame contendo
# somente registros acima desse limite e calcule sua quantidade e percentual
dataset_alta_geracao_4 = dataset_4[
    dataset_4['Potência_CA'] > limiar_70_4]

dataset_alta_geracao_4.head()

,Data_Hora,Inversor,Potência_CC,Potência_CA,Geração_Diaria,Geração_Total
11,26-05-2020 12:15,bvBOhCH3iADSZry,11830.1,1153.83,4028.14,6396364.143
46,15-06-2020 14:30,wCURE6d3bPkepu2,10571.3,1032.07,5366.57,7015064.571
48,25-05-2020 10:15,z9Y9gH1T5YWrNuG,11050.1,1079.86,2174.29,7082812.286
72,13-06-2020 11:30,7JYdWkrLSPkdwr4,11094.5,1082.44,3570.25,7815987.250
76,07-06-2020 13:00,VHMLBKoKgIrUVDU,12663.4,1234.69,4976.71,7382965.714

In [ ]:
quantidade_alta_geracao_4 = dataset_alta_geracao_4.shape[0]

quantidade_total_4 = dataset_4.shape[0]

percentual_alta_geracao_4 = (quantidade_alta_geracao_4 / quantidade_total_4) * 100

print(f'Quantidade de registros de alta geração: {quantidade_alta_geracao_4}')

print(f'Quantidade total de registros: {quantidade_total_4}')

print(f'Percentual da amostra: {percentual_alta_geracao_4:.2f}%')

Quantidade de registros de alta geração: 4159
Quantidade total de registros: 48145
Percentual da amostra: 8.64%

In [ ]:
# 6.Utilize value_counts() em SOURCE_KEY dentro do DataFrame de alta geração
dataset_alta_geracao_4['Inversor'].value_counts()

Inversor
adLQvlD726eNBSB    222
McdE0feGgRqW7Ca    219
ZnxXDlPa8U1GXgE    218
wCURE6d3bPkepu2    208
pkci93gMrogZuBj    208
zBIq5rxdHJRwDNY    201
sjndEbLyjtCKgGv    196
iCRJl6heRkivqQ3    195
VHMLBKoKgIrUVDU    195
1IF53ai7Xc0U56Y    193
YxYtjZvoooNbGkE    192
zVJPv84UY57bAof    190
z9Y9gH1T5YWrNuG    189
ZoEaEvLYb1n2sOq    189
ih0vzX44oOqAx2f    187
3PZuoBAID5Wc2HD    186
uHbuxQJl8lW7ozc    184
rGa61gmuvPhdLxV    182
WRmjgnKYAwPKWDb    180
7JYdWkrLSPkdwr4    161
1BY6WEcLGh8j5v7    137
bvBOhCH3iADSZry    127
Name: count, dtype: int64

In [ ]:
#7.Identifique qual inversor aparece com maior frequência nos registros de alta geração
# e descreva o que esse resultado permite observar, sem concluir desempenho ou falha
# apenas com esse recorte.
inversor_mais_frequente_4 = (
    dataset_alta_geracao_4['Inversor']
    .value_counts()
    .idxmax()
)

quantidade_inversor_4 = (
    dataset_alta_geracao_4['Inversor']
    .value_counts()
    .max()
)

print(f'Inversor mais frequente nos registros de alta geração: {inversor_mais_frequente_4}')

print(f'Quantidade de ocorrências: {quantidade_inversor_4}')

print("O inversor que aparece com maior frequência no "
"conjunto de registros de alta geração é aquele que possui "
"maior participação nesse recorte específico da amostra."
"Esse resultado permite identificar quais inversores aparecem"
" mais frequentemente associados a períodos de potência CA "
"elevada.")

Inversor mais frequente nos registros de alta geração: adLQvlD726eNBSB
Quantidade de ocorrências: 222
O inversor que aparece com maior frequência no conjunto de registros de alta geração é aquele que possui maior participação nesse recorte específico da amostra.Esse resultado permite identificar quais inversores aparecem mais frequentemente associados a períodos de potência CA elevada.

# Dataset 5 — Wind & Solar Energy Production (Kaggle)

Situação

Um operador de um portfólio de fontes renováveis deseja comparar a ocorrência de períodos de alta produção solar e alta produção eólica. Como as duas fontes possuem escalas próprias, cada uma deverá ser comparada com o seu próprio valor máximo.

In [ ]:
dataset_5 = pd.read_csv('Energy Production Dataset.csv')

In [ ]:
# 1.Renomeie as variáveis principais para Geracao_Solar e Geracao_Eolica.
dataset_solar_5 = dataset_5[
    dataset_5['Source'] == 'Solar']

dataset_eolica_5 = dataset_5[
    dataset_5['Source'] == 'Wind']
dataset_solar_5.rename(
    columns={'Production': 'Geracao_Solar'},
    inplace=True)

dataset_eolica_5.rename(
    columns={'Production': 'Geracao_Eolica'},
    inplace=True)

/tmp/ipykernel_184/1657920290.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_solar_5.rename(
/tmp/ipykernel_184/1657920290.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_eolica_5.rename(

In [ ]:
# conferir
print('Solar:')
dataset_solar_5.head()

Solar:

,Date,Start_Hour,End_Hour,Source,Day_of_Year,Day_Name,Month_Name,Season,Geracao_Solar
2,8/1/2024,15,16,Solar,214,Thursday,August,Summer,8835
5,10/18/2024,13,14,Solar,292,Friday,October,Fall,4855
6,4/10/2020,17,18,Solar,101,Friday,April,Spring,3692
13,6/2/2021,15,16,Solar,153,Wednesday,June,Summer,5561
16,5/2/2021,13,14,Solar,122,Sunday,May,Spring,4993

In [ ]:
print('Eólica:')
dataset_eolica_5.head()

Eólica:

,Date,Start_Hour,End_Hour,Source,Day_of_Year,Day_Name,Month_Name,Season,Geracao_Eolica
0,12/18/2022,21,22,Wind,352,Sunday,December,Winter,11400
1,1/29/2024,14,15,Wind,29,Monday,January,Winter,7917
3,11/10/2020,1,2,Wind,315,Tuesday,November,Fall,989
4,12/19/2022,1,2,Wind,353,Monday,December,Winter,12526
7,1/25/2023,0,1,Wind,25,Wednesday,January,Winter,2156

In [ ]:
#2.Determine o valor máximo registrado para cada fonte
max_solar_5 = dataset_solar_5['Geracao_Solar'].max()

print(f'Máxima geração solar: {max_solar_5}')

max_eolica_5 = dataset_eolica_5['Geracao_Eolica'].max()

print(f'Máxima geração eólica: {max_eolica_5}')

Máxima geração solar: 16578
Máxima geração eólica: 23446

In [ ]:
#3.Calcule separadamente 70% do máximo solar e 70% do máximo eólico.
limiar_solar_5 = max_solar_5 * 0.70
limiar_eolica_5 = max_eolica_5 * 0.70

print(f'Limiar de 70% da geração solar: {limiar_solar_5:.2f}')
print(f'Limiar de 70% da geração eólica: {limiar_eolica_5:.2f}')

Limiar de 70% da geração solar: 11604.60
Limiar de 70% da geração eólica: 16412.20

In [ ]:
#4.Crie um DataFrame para registros de alta geração solar e outro para registros de alta geração eólica.
alta_solar_5 = dataset_solar_5[
    dataset_solar_5['Geracao_Solar'] > limiar_solar_5]

alta_solar_5.head()

,Date,Start_Hour,End_Hour,Source,Day_of_Year,Day_Name,Month_Name,Season,Geracao_Solar
77,7/8/2025,13,14,Solar,189,Tuesday,July,Summer,13125
178,3/19/2025,13,14,Solar,78,Wednesday,March,Spring,13786
187,7/16/2025,12,13,Solar,197,Wednesday,July,Summer,16160
207,3/31/2025,12,13,Solar,90,Monday,March,Spring,12441
815,7/11/2025,13,14,Solar,192,Friday,July,Summer,13057

In [ ]:
alta_eolica_5 = dataset_eolica_5[
    dataset_eolica_5['Geracao_Eolica'] > limiar_eolica_5]

alta_eolica_5.head()

,Date,Start_Hour,End_Hour,Source,Day_of_Year,Day_Name,Month_Name,Season,Geracao_Eolica
20,1/3/2024,0,1,Wind,3,Wednesday,January,Winter,17272
103,1/29/2025,0,1,Wind,29,Wednesday,January,Winter,18199
151,12/8/2024,6,7,Wind,343,Sunday,December,Winter,16946
192,11/19/2024,2,3,Wind,324,Tuesday,November,Fall,16568
193,11/2/2025,12,13,Wind,306,Sunday,November,Fall,17124

In [ ]:
#5.Conte os registros de cada DataFrame e calcule seus respectivos percentuais.
quantidade_solar_5 = alta_solar_5.shape[0]

print(f'Registros de alta geração solar: {quantidade_solar_5}')

total_solar_5 = dataset_solar_5.shape[0]

percentual_solar_5 = (quantidade_solar_5 / total_solar_5) * 100

print(f'Percentual de alta geração solar: {percentual_solar_5:.2f}%')

Registros de alta geração solar: 119
Percentual de alta geração solar: 1.80%

In [ ]:
quantidade_eolica_5 = alta_eolica_5.shape[0]

print(f'Registros de alta geração eólica: {quantidade_eolica_5}')

total_eolica_5 = dataset_eolica_5.shape[0]

percentual_eolica_5 = (quantidade_eolica_5 / total_eolica_5) * 100

print(f'Percentual de alta geração eólica: {percentual_eolica_5:.2f}%')

Registros de alta geração eólica: 702
Percentual de alta geração eólica: 2.36%

In [ ]:
#6.Compare qual fonte aparece com maior frequência acima de 70% do seu próprio máximo.
if percentual_solar_5 > percentual_eolica_5:
    print('A geração solar aparece com maior frequência acima de 70% do próprio máximo.')

elif percentual_eolica_5 > percentual_solar_5:
    print('A geração eólica aparece com maior frequência acima de 70% do próprio máximo.')

else:
    print('As duas fontes apresentam a mesma frequência.')

A geração eólica aparece com maior frequência acima de 70% do próprio máximo.

In [ ]:
#7.Explique por que não seria adequado utilizar diretamente o mesmo valor numérico de potência como limite para as duas fontes sem antes observar a escala de cada variável.
print("Não seria adequado utilizar diretamente o mesmo valor numérico de potência como limite para as duas fontes porque a geração solar e a geração eólica podem apresentar escalas e valores máximos diferentes.")

Não seria adequado utilizar diretamente o mesmo valor numérico de potência como limite para as duas fontes porque a geração solar e a geração eólica podem apresentar escalas e valores máximos diferentes.

# Dataset 6 — Individual Household Electric Power Consumption (UCI)
Situação

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente

In [ ]:
# Carregar os dados externos do arquivo .csv
dataset_6 = pd.read_csv('dados_externos.csv')

In [ ]:
# 1.Carregue a nova amostra e organize os atributos utilizando nomes mais simples
dataset_6.rename(columns={
    'Global_active_power': 'Potencia_Ativa',
    'Global_reactive_power': 'Potencia_Reativa',
    'Voltage': 'Tensao',
    'Global_intensity': 'Corrente',
    'Sub_metering_1': 'Medicao_1',
    'Sub_metering_2': 'Medicao_2',
    'Sub_metering_3': 'Medicao_3'}, inplace=True)

dataset_6.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Medicao_1,Medicao_2,Medicao_3
0,1.502,0.074,240.17,6.4,0,0,18
1,0.374,0.264,245.50,1.8,0,2,0
2,0.620,0.300,239.85,3.0,0,1,1
3,0.280,0.200,235.72,1.4,0,0,0
4,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# 2.Determine o valor máximo de potência ativa
maior_potencia_6 = dataset_6['Potencia_Ativa'].max()

print(f'O valor máximo de potência ativa foi: {maior_potencia_6:.4f} kW')

O valor máximo de potência ativa foi: 11.1220 kW

In [ ]:
# 3.Calcule 75% do valor máximo e crie um DataFrame contendo registros acima desse limite.
limiar_75_6 = maior_potencia_6 * 0.75

print(f'75% do valor máximo de potência ativa: {limiar_75_6:.4f} kW')

75% do valor máximo de potência ativa: 8.3415 kW

In [ ]:
# Registros acima do limite
dataset_potencia_elevada_6 = dataset_6[
    dataset_6['Potencia_Ativa'] > limiar_75_6]

dataset_potencia_elevada_6.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Medicao_1,Medicao_2,Medicao_3
3132,8.540,0.238,236.23,36.0,80,35,17
27983,10.290,0.302,230.90,44.6,35,66,17
31023,9.708,0.372,231.37,42.0,37,69,17
53700,8.444,0.058,232.87,36.4,5,72,17
55060,8.898,0.264,234.13,38.0,73,22,18

In [ ]:
# 4. Calcule a quantidade e o percentual de registros selecionados.
quantidade_elevada_6 = dataset_potencia_elevada_6.shape[0]

quantidade_total_6 = dataset_6.shape[0]

percentual_elevada_6 = (quantidade_elevada_6 / quantidade_total_6) * 100

print(f'Quantidade de registros selecionados: {quantidade_elevada_6}')
print(f'Quantidade total de registros: {quantidade_total_6}')
print(f'Percentual da amostra: {percentual_elevada_6:.2f}%')

Quantidade de registros selecionados: 141
Quantidade total de registros: 1434496
Percentual da amostra: 0.01%

In [ ]:
# 5.Calcule a corrente média da amostra.
corrente_media_6 = dataset_6['Corrente'].mean()

print(f'A corrente média da amostra foi: {corrente_media_6:.4f} A')

A corrente média da amostra foi: 4.6261 A

In [ ]:
# 6. Crie um segundo DataFrame contendo simultaneamente potência ativa acima de 75% do máximo e corrente acima da média.
dataset_potencia_e_corrente_6 = dataset_6[
    (dataset_6['Potencia_Ativa'] > limiar_75_6) &
    (dataset_6['Corrente'] > corrente_media_6)]

dataset_potencia_e_corrente_6.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Medicao_1,Medicao_2,Medicao_3
3132,8.540,0.238,236.23,36.0,80,35,17
27983,10.290,0.302,230.90,44.6,35,66,17
31023,9.708,0.372,231.37,42.0,37,69,17
53700,8.444,0.058,232.87,36.4,5,72,17
55060,8.898,0.264,234.13,38.0,73,22,18

In [ ]:
quantidade_segundo_6 = dataset_potencia_e_corrente_6.shape[0]

percentual_segundo_6 = (quantidade_segundo_6 / quantidade_total_6) * 100

print(f'Quantidade de registros: {quantidade_segundo_6}')
print(f'Percentual da amostra: {percentual_segundo_6:.2f}%')

Quantidade de registros: 141
Percentual da amostra: 0.01%

In [ ]:
# 7.Compare os dois conjuntos e explique o efeito da inclusão da corrente como segunda condição.
print(f'Registros com potência acima de 75%: {quantidade_elevada_6}')

print(f'Registros com potência acima de 75% e corrente acima da média: {quantidade_segundo_6}')

print(f'Registros eliminados pela inclusão da corrente: {quantidade_elevada_6 - quantidade_segundo_6}')

Registros com potência acima de 75%: 141
Registros com potência acima de 75% e corrente acima da média: 141
Registros eliminados pela inclusão da corrente: 0